app/urls.py
# app URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#    https://docs.djangoproject.com/en/3.1/topics/http/urls/
# Examples:
# Function views
#    1. Add an import:  from my_app import views
#    2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#    1. Add an import:  from other_app.views import Home
#    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#    1. Import the include() function: from django.urls import include, path
#    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name="inicio"),
    path('', include('usuarios.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from usuarios import views

urlpatterns = [
    path('accounts/login/', views.Login.as_view(), name='login'),
    path('logout/', login_required(views.logoutUsuario), name='logout'),
    path('registrar', views.Registrar.as_view(), name='registrar'),
    path('elige', views.elige, name='elegir'),
    path('crearProyecto', login_required(
        views.CrearProyecto.as_view()), name="crearProyecto"),
    path('serFreelancer', login_required(
        views.SerFreelancer.as_view()), name='serFreelancer'),
    path('perfil', login_required(views.Perfil.as_view()), name='perfil'),
    path('misProyectos', login_required(views.MisProyectos), name='misProyectos'), 
    path('editarPerfil', login_required(views.EditarPerfil.as_view()), name='editarPerfil'),
    path('buscarProyectos', views.buscarProyectos, name='buscarProyectos'),
    path('editarProyecto', login_required(views.EditarProyecto.as_view()), name='editarProyecto'),
    path('solicitudesFreel', login_required(views.solicitudesF), name='solicitudesF'),
    path('cantratados', login_required(views.fContratados), name='fContratados'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import RegexValidator
from django.contrib.postgres.fields import ArrayField


class UsuarioManager(BaseUserManager):
    def create_user(self, nombre, correo, password):
        # metodo que se utilizara para crear usuarios
        usuario = self.model(nombre=nombre, correo=correo)
        usuario.set_password(password)
        usuario.save()
        return usuario

    def create_superuser(self, nombre, correo, password):
        # metodo que se utilizara para crear usuarios administradores
        usuario = self.create_user(
            nombre=nombre,
            correo=correo,
            password=password
        )
        usuario.admin = True
        usuario.save()
        return usuario


class Usuario(AbstractBaseUser):
    # modelo que enlazara con la tabla de la base de datos usuario
    nombre = models.CharField(
        'Nombre de usuario', max_length=50, unique=True)

    imagen = models.ImageField(
        'Imagen de perfil', upload_to='perfil/',
        height_field=None, width_field=None,
        max_length=200, blank=True, null=True
    )

    correo = models.EmailField(
        'Correo electronico', max_length=50,
        blank=False, null=False, unique=True
    )

    admin = models.BooleanField(default=False)
    activo = models.BooleanField(default=True)
    objects = UsuarioManager()

    USERNAME_FIELD = 'nombre'
    REQUIRED_FIELDS = ['correo']

    def __str__(self):
        # metodo de sobrescritura de la funcion to_string esto representa
        # que se mostrara al imprimir el objeto usuario
        return f'nombre: {self.nombre}, correo: {self.correo}, admin: {self.admin}'

    def has_perm(self, perm, obj=None):
        #  metodo para poder usar este modelo en el administrador de jango
        #  es llamado en la parte de los permisos de quien puede o no acceder
        #  administrador de django y lo maneja automaticament
        return True

    def has_module_perms(self, app_label):
        #  metodo utilizado para el admin de djando recibe como parametro la
        #  etiqueta de la aplicación donde esta este modelo
        return True

    @property
    def is_staff(self):
        # metodo que sera utilizado para saber si un usuario es administrador
        # o usuario comun
        return self.admin


class Proyecto(models.Model):
    #  Modelo para la tabla proyecto en la base de datos
    #  Autor: Lesther Valladares
    #  Version: 0.0.1
    #  Atributos:
    #    -  usuario: Llave foranea de el usuario que crea el proyecto
    #    -  tipo: Representa el tipo de categoria al que pertenece el proyecto
    #    -  titulo: Contiene el titulo del proyecto(obligatorio)
    #    -  descripcion: Contiene una descripcon del proyecto(obligatorio)
    #    -  xp: Campo numerico para puntuar la experiencia requerida del freelancer
    #    -  fecha_inicio: Fecha de creacion del proyecto
    #    -  fecha_fin: Fecha en la que se espera que termine el proyecto
    usuario = models.ForeignKey(Usuario, null=False, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=30)
    titulo = models.CharField(max_length=40)
    descripcion = models.CharField(max_length=500)
    xp = models.IntegerField()
    moneda = models.CharField(max_length=2)
    presupuesto = models.IntegerField()
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()


class Freelancer(models.Model):
    #  Modelo para la tabla proyecto en la base de datos
    #  Autor: Lesther Valladares
    #  Fecha: 10/04/2021
    #  Version: 0.0.1
    #  Atributos:
    #    -  usuario: Llave foranea de el usuario que crea el proyecto (relación 1 a 1)
    #    -  nombre:
    #    -  apellido:
    #    -  correo: Correo electronico de trabajo del freelancer
    #    -  profesion: campo que contiene la profesion a la que se dedica el freelancer
    #    -  xp: Campo numerico para puntuar la experiencia requerida del freelancer
    #    -  telefono: numero telefonico del freelancer con el que se comunicara las empresas
    #    -  idiomas: Lista de idiomas que domina el freelancer
    #    -  descripcion: Contiene una descripcon de las habilidades del freelancer(obligatorio)
    usuario = models.OneToOneField(
        Usuario, null=False, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=15)
    apellido = models.CharField(max_length=15)
    correo = models.EmailField(
        max_length=50, blank=False, null=False, unique=True)
    profesion = models.CharField(max_length=30)
    xp = models.IntegerField()
    # tel: Campo usado para formatear el número de telefono y que sea valido
    tel = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="El número de telefono debe ingresarse en el formato: '+999999999'. hasta 15 digitos permitidos.")

    telefono = models.CharField(validators=[tel], max_length=17, blank=False)

    idiomas = ArrayField(models.CharField(max_length=10))
    descripcion = models.CharField(max_length=500)


class Notificaciones(models.Model):
    proyecto = models.ForeignKey(
        Proyecto, null=False, on_delete=models.CASCADE)
    freelancer = models.ForeignKey(
        Freelancer, null=False, on_delete=models.CASCADE)
    asunto = models.CharField(max_length=40, null=False)
    solicitud = models.CharField(max_length=320, null=False)
    noLeido = models.BooleanField(default=True)
    borrado = models.BooleanField(default=False)


class Contrataciones(models.Model):
    proyecto = models.ForeignKey(
        Proyecto, null=False, on_delete=models.CASCADE)
    freelancer = models.ForeignKey(
        Freelancer, null=False, on_delete=models.CASCADE)
    fechaContratacion = models.DateTimeField(null=False)
    activa = models.BooleanField(default=True)

usuarios/templates/usuarios/buscarProyectos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    {% include 'frames/head.html' %}
    <style type="text/css">
        .mPcard {
            padding: 2% 3% 0% 3%;
        }

        @media only screen and (max-width : 992px) {
            .mPcard {
                padding: 2% 2% 0% 2%;
            }
        }
    </style>
</head>

<body>
    {% include 'frames/navbar.html' %}
    <main>
        {% if listaObjetos %}
        <div class="row mPcard">
            {% for proyecto in listaObjetos %}
            <div class="col s12 m6">
                <div class="card" style="min-height: 100%;">
                    <div class="card-title center grey darken-2" style="color:#d6d6d6; font-weight: bold;">
                        {{proyecto.tipo}}
                    </div>
                    <div class="card-content">
                        <div class="row">

                            <div class="col s12 m6">
                                <label style="font-size: 15px;">{{proyecto.titulo}}</label>
                                {% if proyecto.tipo == 'Programacion Web' %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/web.jpg' %}">
                                {% elif proyecto.tipo == 'Tiendas Online' %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/shop.png' %}">
                                {% elif proyecto.tipo == 'Landing page' %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/lp.jpg' %}">
                                {% elif proyecto.tipo == 'Aplicaciones Moviles' %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/app.png' %}">
                                {% elif proyecto.tipo == 'Sistemas para Ordenadores' %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/so.jpg' %}">
                                {% elif proyecto.tipo == "Servidores" %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/server.png' %}">
                                {% elif proyecto.tipo == 'Bases de Datos' %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/db.png' %}">
                                {% elif proyecto.tipo == 'Infraestructura' %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/redes.png' %}">
                                {% elif proyecto.tipo == 'Diseño' %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/dg.jpg' %}">
                                {% else %}
                                <img style="height: 120px;  margin-top: 5%;" src="{% static 'img/proyectos/o.jpg' %}">
                                {% endif %}
                                <div class="row" style="min-height: 45px;">
                                    <div class="col s1">
                                        <i class="material-icons">work</i>
                                    </div>
                                    <div class="col s10">
                                        <label style="font-size: 15px;">Experiencia
                                            Profesional:
                                            {% if proyecto.xp is 1 %}
                                            {{"Básico"}}
                                            {% elif proyecto.xp is 2 %}
                                            {{"Medio"}}
                                            {% elif proyecto.xp == 3 %}
                                            {{"Intermedio"}}
                                            {% else%}
                                            {{"Avanzado"}}
                                            {% endif %}
                                        </label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s12">
                                        <label style="font-size: 15px;">Presupuesto: {{proyecto.moneda}} {{proyecto.presupuesto}}</label>
                                    </div>
                                    <div class="col s1">
                                        <i class="material-icons">short_text</i>
                                    </div>
                                    <div class="col s10">
                                        <label style="font-size: 15px;">
                                            Fecha de entrega: {{proyecto.fecha_fin}}
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="col s12 m5" style="margin-bottom: 20px;">
                                <label style="font-size: 15px;">Descripción:</label>
                                <textarea disabled class="auto_scroll"
                                    style="width: 105%; max-height: 240px; resize: none; border: none;">{{proyecto.descripcion}}</textarea>
                            </div>

                            <div class="col s12 center">
                                <!-- Boton para desplegar modal de postularse -->
                                <button data-target="modal{{proyecto.id}}" class="btn green darken-1 modal-trigger">
                                    Postularse
                                </button>

                                <!-- Modal postularse -->
                                <div id="modal{{proyecto.id}}" class="modal modal-fixed-footer"
                                    style="max-width: 400px; min-width: 310px; height: 420px;">
                                    <div class="modal-content">
                                        <h4>Solicitud de participación</h4>
                                        <p>solicitud para postularte al proyecto {{proyecto.titulo}}</p>
                                        <br>
                                        <textarea id="txt-solicitud{{proyecto.id}}" class="grey darken-4"
                                            style="resize: none; max-width: 100%; height:155px;border: 1px dotted #848484">{{texto}}</textarea>
                                    </div>
                                    <div class="modal-footer">
                                        <a class="modal-close waves-effect waves-red btn-flat red-text">
                                            Cancelar
                                        </a>
                                        <a onclick="postularse('{{proyecto.id}}', '{{proyecto.titulo}}')"
                                            class="modal-close waves-effect waves-green btn-flat">
                                            Enviar
                                        </a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            {% endfor %}

        </div>

        <div class="center" style="padding-bottom: 10px;">
            {% include 'frames/paginacion.html' %}
        </div>
        {% else %}
        <div class="container">
            <div class="materialert info" style="width: 100%;">
                <div class="material-icons">info</div>No hay proyectos en la búsqueda
            </div>
        </div>
        {% endif %}
    </main>

    <script src="{% static 'js/WQuick.js' %}"></script>
    {% include 'frames/autocomplete.html' %}
    <script src="{% static 'js/getCookie.js' %}"></script>
    <script src="{% static 'js/enviarDatos.js' %}"></script>
    <script>
        function postularse(idProyecto, asunto) {
            let datos = new FormData();
            let solicitud = document.getElementById('txt-solicitud'+idProyecto).value
            datos.append('idProyecto', idProyecto)
            datos.append('solicitud', solicitud)
            datos.append('asunto', asunto)
            enviar(datos, 'post', {}, '{% url "buscarProyectos" %}')
        }
    </script>
</body>

</html>

usuarios/templates/usuarios/editarPerfil.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    {% include 'frames/head.html' %}
</head>

<body>
    {% include 'frames/navbar.html' %}
    {% include 'frames/sidebar.html' %}
    <main>
        {% if form.nombre.errors %}
        <a id="alerta" class="alerta" style="display: none;"
            onclick="alerta('{{form.nombre.errors.as_text}}')">Toast!</a>
        {% endif %}

        {% if form.apellido.errors %}
        <a id="alerta" class="alerta" style="display: none;"
            onclick="alerta('{{form.apellido.errors.as_text}}')">Toast!</a>
        {% endif %}

        {% if form.correo.errors %}
        <a id="alerta" class="alerta" style="display: none;"
            onclick="alerta('{{form.correo.errors.as_text}}')">Toast!</a>
        {% endif %}

        {% if form.profesion.errors %}
        <a id="alerta" class="alerta" style="display: none;"
            onclick="alerta('{{form.profesion.errors.as_text}}')">Toast!</a>
        {% endif %}

        {% if form.telefono.errors %}
        <a id="alerta" class="alerta" style="display: none;"
            onclick="alerta('{{form.telefono.errors.as_text}}')">Toast!</a>
        {% endif %}

        {% if form.descripcion.errors %}
        <a id="alerta" class="alerta" style="display: none;"
            onclick="alerta('{{form.descripcion.errors.as_text}}')">Toast!</a>
        {% endif %}

        {% if form.idiomas.errors %}
        <a id="alerta" class="alerta" style="display: none;"
            onclick="alerta('{{form.idiomas.errors.as_text}}')">Toast!</a>
        {% endif %}

        <div class="row mcard">
            <div class="col s12 m10 offset-m1">
                <section style="padding: 5px;">
                    <div class="row">
                        <div class="col s12 m10 offset-m1">
                            <div class="container-fluid">
                                <form id="frm-editarfreelancer" method="POST">{% csrf_token %}
                                    <div class="container-fluid center">
                                        <label style="font-size: 20px;">Edita tus Datos</label>
                                        <br><br>
                                    </div>

                                    <div class="col s12 m6">
                                        <div class="input-field col s12">
                                            <i class="material-icons prefix">description</i>
                                            {{form.nombre}}
                                            <label for="id_nombre">Nombre</label>
                                        </div>

                                        <div class="input-field col s12">
                                            <i class="material-icons prefix">description</i>
                                            {{form.apellido}}
                                            <label for="txt-apellido">Apellido</label>
                                        </div>

                                        <div class="col s1">
                                            <i class="material-icons">
                                                language
                                            </i>
                                        </div>
                                        <div class="col s11">
                                            <label style="font-size: 15px; margin-left: 10px;">Idiomas:</label>
                                        </div>
                                        {{form.idiomas}}
                                        <div class="col s5">
                                            <p>
                                                <label>
                                                    <input id='Ingles'
                                                        {% if 'Ingles' in freelancer.idiomas %}{{'checked'}}{% endif %}
                                                        type="checkbox" value='0' />
                                                    <span style="font-size: small;">Ingles</span>
                                                </label>
                                            </p>
                                            <p>
                                                <label>
                                                    <input type="checkbox"
                                                        {% if 'Chino' in freelancer.idiomas %}{{'checked'}}{% endif %}
                                                        value='1' />
                                                    <span style="font-size: small;">Chino</span>
                                                </label>
                                            </p>
                                            <p>
                                                <label>
                                                    <input type="checkbox"
                                                        {% if 'Alemán' in freelancer.idiomas %}{{'checked'}}{% endif %}
                                                        value='2' />
                                                    <span style="font-size: small;">Alemán</span>
                                                </label>
                                            </p>
                                        </div>
                                        <div class="col s6">
                                            <p>
                                                <label>
                                                    <input type="checkbox"
                                                        {% if 'Francés' in freelancer.idiomas %}{{'checked'}}{% endif %}
                                                        value='3' />
                                                    <span style="font-size: small;">Francés</span>
                                                </label>
                                            </p>
                                            <p>
                                                <label>
                                                    <input type="checkbox"
                                                        {% if 'Portugués' in freelancer.idiomas %}{{'checked'}}{% endif %}
                                                        value='4' />
                                                    <span style="font-size: small;">Portugués</span>
                                                </label>
                                            </p>
                                            <p>
                                                <label>
                                                    <input type="checkbox"
                                                        {% if 'Japonés' in freelancer.idiomas %}{{'checked'}}{% endif %}
                                                        value='5' />
                                                    <span style="font-size: small;">Japonés</span>
                                                </label>
                                            </p>
                                        </div>
                                        <div class="input-field col s12">
                                            <div class="select-wrapper">
                                                {{form.xp}}
                                            </div>
                                            <label>Experiencia profesional</label>
                                        </div>
                                    </div>

                                    <div class="col s12 m6" style="margin-bottom: 20px;">
                                        <div class="input-field col s12">
                                            <i class="material-icons prefix">mail</i>
                                            {{form.correo}}
                                            <label for="txt-correo">Correo electrónico</label>
                                        </div>

                                        <div class="input-field col s12">
                                            <i class="material-icons prefix">work</i>
                                            {{form.profesion}}
                                            <label for="txt-profesion">Profesión</label>
                                        </div>

                                        <div class="input-field col s12">
                                            <i class="material-icons prefix">call</i>
                                            {{form.telefono}}
                                            <label for="txt-telefono">Teléfono</label>
                                        </div>

                                        <div class="col s1">
                                            <i class="material-icons">short_text</i>
                                        </div>
                                        <div class="col s11">
                                            <label class="grey-text text-lighten-1"
                                                style="font-size: 15px;">Descripción:</label>
                                            <div>
                                                {{form.descripcion}}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="center" style="margin-bottom: 20px;">
                                        <a href="{% url 'perfil' %}" class="btn grey darken-1">Cancelar</a>
                                        <button id="btn-guardar" type="submit" class="btn green darken-1;">Guardar
                                            Cambios </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </main>

    <script src="{% static 'js/WQuick.js' %}"></script>
    {% include 'frames/autocomplete.html' %}
    <script>
        var fNombre = '{{freelancer.nombre}}';
        var fApellido = '{{freelancer.apellido}}';
        var fDescripcion = `{{freelancer.descripcion}}`;
        var fTelefono = '{{freelancer.telefono}}';
        var fCorreo = '{{freelancer.correo}}';
        var fProfesion = '{{freelancer.profesion}}';
        var fXp = '{{freelancer.xp}}';
    </script>
    <script src="{% static 'js/editarPerfil.js' %}"></script>
</body>

</html>

usuarios/templates/usuarios/editarProyecto.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    {% include 'frames/head.html' %}
</head>

<body>
    {% include 'frames/navbar.html' %}
    {% include 'frames/sidebar.html' %}
    <main>
        <div class="row mcard" style="padding-left: 2%; padding-right: 2%;">
            <div class="card col s12 m10 offset-m1">
                <div class="card-title center">
                    <label style="font-size: 20px;">Edita tu proyecto</label>
                    <br>
                </div>

                <div class="card-content">
                    <form id="frm-editarproyecto" method="POST">{% csrf_token %}
                        <div class="input-field col s12 m6">
                            <i class="material-icons prefix">book</i>
                            {{form.tipo}}
                            <label for="id_tipo">Tipo</label>
                        </div>
                        
                        <div class="input-field col s12 m6">
                            <i class="material-icons prefix">title</i>
                            {{form.titulo}}
                            <label for="id_titulo">Titulo</label>
                        </div>
                        <div class="input-field col s12 m6">
                            <i class="material-icons prefix">work</i>
                            {{form.xp}}
                            <label for="id_xp">Experiencia profesional</label>
                        </div>

                        <div class="col s12 m6">
                            <div class="input-field">
                                {{ form.fecha }}
                                <label for="data">Fecha en que necesitas tu Proyecto</label>
                            </div>
                        </div>

                        <div class="input-field col s5 m2">
                            <i class="material-icons prefix">money</i>
                            {{form.moneda}}
                            <label for="id_moneda">Presupuesto</label>
                        </div>

                        <div class="col s7 m4">
                            {{form.presupuesto}}
                        </div>

                        <div class="col s12">
                            <label for="id_descripcion" class="grey-text text-lighten-1">Descripción:</label>
                            <div>
                                {{form.descripcion}}
                            </div>
                        </div>

                        <div class="col s12"><br></div>
                        <div class="container-fluid center">
                            <div class="col s8 offset-s2">
                                <button id="btn-guardar" class="btn">Guardar</button>
                            </div>
                            <div class="col s12"><br></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

    <script src="{% static 'js/WQuick.js' %}"></script>
    {% include 'frames/autocomplete.html' %}
    <script>
        var tipo = '{{proyecto.tipo|escape}}'
        var titulo = '{{proyecto.titulo|escape}}'
        var xp = '{{proyecto.xp|escape}}'
        var fecha = '{{fecha|escape}}'
        var moneda = '{{proyecto.moneda|escape}}'
        var presupuesto = '{{proyecto.presupuesto|escape}}'
        var descripcion = `{{proyecto.descripcion|escape}}`

        document.getElementById('id_presupuesto').value = presupuesto;
        document.getElementById('id_titulo').value = titulo;
        document.getElementById('id_tipo').value = tipo;
        document.getElementById('id_moneda').value = moneda;
        document.getElementById('data').value = fecha;
        document.getElementById('id_descripcion').value = descripcion;
        document.getElementById('id_xp').value = xp;
    </script>
</body>

</html>